import enum


class ClientSource(str, enum.Enum):
    WEB_PAGE = "WEB_PAGE"
    WHATSAPP = "WHATSAPP"
    FACEBOOK = "FACEBOOK"
    INSTAGRAM = "INSTAGRAM"
    REFERRAL = "REFERRAL"
    PHONE_CALL = "PHONE_CALL"
    OTHER = "OTHER"


class ClientStatus(str, enum.Enum):
    PENDIENTE_DE_REVISION = "PENDIENTE_DE_REVISION"
    RECHAZADO = "RECHAZADO"
    APROBADO_PARA_ONBOARDING = "APROBADO_PARA_ONBOARDING"
    EN_CARGA_DATOS = "EN_CARGA_DATOS"
    DOCUMENTOS_EN_REVISION = "DOCUMENTOS_EN_REVISION"
    LISTO_PARA_TABLERO = "LISTO_PARA_TABLERO"
    ONBOARDING_EN_PROGRESO = "ONBOARDING_EN_PROGRESO"
    ONBOARDING_COMPLETADO = "ONBOARDING_COMPLETADO"
    INACTIVO = "INACTIVO"


class DocumentType(str, enum.Enum):
    SSN_CARD = "SSN_CARD"
    DRIVERS_LICENSE_FRONT = "DRIVERS_LICENSE_FRONT"
    DRIVERS_LICENSE_BACK = "DRIVERS_LICENSE_BACK"
    PASSPORT = "PASSPORT"
    GREEN_CARD = "GREEN_CARD"
    WORK_PERMIT = "WORK_PERMIT"
    UTILITY_BILL = "UTILITY_BILL"
    BANK_STATEMENT = "BANK_STATEMENT"


class DocumentVerificationStatus(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    EN_PROCESO = "EN_PROCESO"
    APROBADO = "APROBADO"
    RECHAZADO = "RECHAZADO"
    PROXIMO_A_VENCER = "PROXIMO_A_VENCER"


class TaskStatus(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    EN_PROGRESO = "EN_PROGRESO"
    EN_REVISION = "EN_REVISION"
    COMPLETADA = "COMPLETADA"


class AddressType(str, enum.Enum):
    CURRENT = "CURRENT"
    PREVIOUS = "PREVIOUS"


class NotificationEventType(str, enum.Enum):
    NEW_CLIENT_PENDING_REVIEW = "NEW_CLIENT_PENDING_REVIEW"
    CLIENT_REJECTED = "CLIENT_REJECTED"
    CLIENT_APPROVED = "CLIENT_APPROVED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    DOCUMENT_EXPIRING_SOON = "DOCUMENT_EXPIRING_SOON"
    CLIENT_DATA_COMPLETE = "CLIENT_DATA_COMPLETE"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_COMMENTED = "TASK_COMMENTED"
