import enum


class ClientSource(str, enum.Enum):
    """Legacy enum — el catálogo vivo está en la tabla `sources`."""

    WEB_PAGE = "WEB_PAGE"
    WHATSAPP = "WHATSAPP"
    FACEBOOK = "FACEBOOK"
    INSTAGRAM = "INSTAGRAM"
    REFERRAL = "REFERRAL"
    PHONE_CALL = "PHONE_CALL"
    INFLUENCERS = "INFLUENCERS"
    LANDING = "LANDING"
    OTHER = "OTHER"


class ProspectStatus(str, enum.Enum):
    PENDIENTE_CONTACTAR = "PENDIENTE_CONTACTAR"
    LEAD_CONTACTADO = "LEAD_CONTACTADO"
    LEAD_CERRADO = "LEAD_CERRADO"
    CONTRATO_ENVIADO = "CONTRATO_ENVIADO"
    PAGO_COMPLETADO = "PAGO_COMPLETADO"


class ProspectHistoryEventType(str, enum.Enum):
    STATUS_CHANGE = "STATUS_CHANGE"
    NOTE = "NOTE"
    CALENDLY_LINKED = "CALENDLY_LINKED"
    CALENDLY_RESCHEDULED = "CALENDLY_RESCHEDULED"
    CONTRACT_SENT = "CONTRACT_SENT"
    CONTRACT_SIGNED = "CONTRACT_SIGNED"
    PAYMENT_LINKED = "PAYMENT_LINKED"
    PAYMENT_CANCELLED = "PAYMENT_CANCELLED"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    CONVERTED = "CONVERTED"


class ProductCode(str, enum.Enum):
    CREDIT = "CREDIT"
    COURSE = "COURSE"
    MENTORSHIP = "MENTORSHIP"


EDUCATION_PRODUCT_CODES = frozenset({ProductCode.COURSE.value, ProductCode.MENTORSHIP.value})


class ClientStatus(str, enum.Enum):
    PENDIENTE_DE_REVISION = "PENDIENTE_DE_REVISION"
    RECHAZADO = "RECHAZADO"
    APROBADO_PARA_ONBOARDING = "APROBADO_PARA_ONBOARDING"
    EN_CARGA_DATOS = "EN_CARGA_DATOS"
    DOCUMENTOS_EN_REVISION = "DOCUMENTOS_EN_REVISION"
    LISTO_PARA_TRABAJAR = "LISTO_PARA_TRABAJAR"
    ONBOARDING_EN_PROGRESO = "ONBOARDING_EN_PROGRESO"
    ONBOARDING_COMPLETADO = "ONBOARDING_COMPLETADO"
    INACTIVO = "INACTIVO"
    # Portal activo por curso/mentoría; no entra al pipeline de asesoría.
    SIN_ASESORIA = "SIN_ASESORIA"


class DocumentType(str, enum.Enum):
    SSN_CARD = "SSN_CARD"
    DRIVERS_LICENSE_FRONT = "DRIVERS_LICENSE_FRONT"
    DRIVERS_LICENSE_BACK = "DRIVERS_LICENSE_BACK"
    PASSPORT = "PASSPORT"
    GREEN_CARD = "GREEN_CARD"
    WORK_PERMIT = "WORK_PERMIT"
    UTILITY_BILL = "UTILITY_BILL"
    BANK_STATEMENT = "BANK_STATEMENT"


class DocumentVerificationStatus(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    EN_PROCESO = "EN_PROCESO"
    APROBADO = "APROBADO"
    RECHAZADO = "RECHAZADO"
    PROXIMO_A_VENCER = "PROXIMO_A_VENCER"


class TaskStatus(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    EN_PROGRESO = "EN_PROGRESO"
    EN_REVISION = "EN_REVISION"
    COMPLETADA = "COMPLETADA"


class BoardCardLabel(str, enum.Enum):
    """Etiqueta visual de la card (independiente del status de workflow)."""

    URGENTE = "URGENTE"
    RECHAZADA = "RECHAZADA"
    DENEGADA = "DENEGADA"
    APROBADA = "APROBADA"
    PENDIENTE = "PENDIENTE"


class AddressType(str, enum.Enum):
    CURRENT = "CURRENT"
    PREVIOUS = "PREVIOUS"


class NotificationEventType(str, enum.Enum):
    NEW_CLIENT_PENDING_REVIEW = "NEW_CLIENT_PENDING_REVIEW"
    CLIENT_REJECTED = "CLIENT_REJECTED"
    CLIENT_APPROVED = "CLIENT_APPROVED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    DOCUMENT_EXPIRING_SOON = "DOCUMENT_EXPIRING_SOON"
    BOARD_ATTACHMENT_REJECTED = "BOARD_ATTACHMENT_REJECTED"
    CLIENT_DATA_COMPLETE = "CLIENT_DATA_COMPLETE"
    CLIENT_ONBOARDING_INCOMPLETE = "CLIENT_ONBOARDING_INCOMPLETE"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_COMMENTED = "TASK_COMMENTED"
    CALENDLY_EVENT_SCHEDULED = "CALENDLY_EVENT_SCHEDULED"
    DOCUSIGN_ENVELOPE_COMPLETED = "DOCUSIGN_ENVELOPE_COMPLETED"
    PAYMENT_LINK_COMPLETED = "PAYMENT_LINK_COMPLETED"
    PROSPECT_CONVERTED = "PROSPECT_CONVERTED"
